//* Admin Auth

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGIN_RESET = "ADMIN_LOGIN_RESET";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

//* CMS CONSTANTS

export const ADMIN_PAGELIST_REQUEST = "ADMIN_PAGELIST_REQUEST";
export const ADMIN_PAGELIST_SUCCESS = "ADMIN_PAGELIST_SUCCESS";
export const ADMIN_PAGELIST_FAIL = "ADMIN_PAGELIST_FAIL";

export const ADMIN_ADDPAGE_REQUEST = "ADMIN_ADDPAGE_REQUEST";
export const ADMIN_ADDPAGE_SUCCESS = "ADMIN_ADDPAGE_SUCCESS";
export const ADMIN_ADDPAGE_FAIL = "ADMIN_ADDPAGE_FAIL";
export const ADMIN_ADDPAGE_RESET = "ADMIN_ADDPAGE_RESET";

export const ADMIN_PAGESTATUS_REQUEST = "ADMIN_PAGESTATUS_REQUEST";
export const ADMIN_PAGESTATUS_SUCCESS = "ADMIN_PAGESTATUS_SUCCESS";
export const ADMIN_PAGESTATUS_FAIL = "ADMIN_PAGESTATUS_FAIL";

//* MASTER SETTINGS CONSTANTS

export const ADMIN_COUNTRYLIST_REQUEST = "ADMIN_COUNTRYLIST_REQUEST";
export const ADMIN_COUNTRYLIST_SUCCESS = "ADMIN_COUNTRYLIST_SUCCESS";
export const ADMIN_COUNTRYLIST_FAIL = "ADMIN_COUNTRYLIST_FAIL";

export const ADMIN_ADDCOUNTRY_REQUEST = "ADMIN_ADDCOUNTRY_REQUEST";
export const ADMIN_ADDCOUNTRY_SUCCESS = "ADMIN_ADDCOUNTRY_SUCCESS";
export const ADMIN_ADDCOUNTRY_FAIL = "ADMIN_ADDCOUNTRY_FAIL";
export const ADMIN_ADDCOUNTRY_RESET = "ADMIN_ADDCOUNTRY_RESET";

export const ADMIN_COUNTRYDETAIL_REQUEST = "ADMIN_COUNTRYDETAIL_REQUEST";
export const ADMIN_COUNTRYDETAIL_SUCCESS = "ADMIN_COUNTRYDETAIL_SUCCESS";
export const ADMIN_COUNTRYDETAIL_FAIL = "ADMIN_COUNTRYDETAIL_FAIL";

export const ADMIN_DELETECOUNTRY_REQUEST = "ADMIN_DELETECOUNTRY_REQUEST";
export const ADMIN_DELETECOUNTRY_SUCCESS = "ADMIN_DELETECOUNTRY_SUCCESS";
export const ADMIN_DELETECOUNTRY_FAIL = "ADMIN_DELETECOUNTRY_FAIL";

export const ADMIN_COUNTRYSTATUS_REQUEST = "ADMIN_COUNTRYSTATUS_REQUEST";
export const ADMIN_COUNTRYSTATUS_SUCCESS = "ADMIN_COUNTRYSTATUS_SUCCESS";
export const ADMIN_COUNTRYSTATUS_FAIL = "ADMIN_COUNTRYSTATUS_FAIL";

export const ADMIN_UPDATECOUNTRY_REQUEST = "ADMIN_UPDATECOUNTRY_REQUEST";
export const ADMIN_UPDATECOUNTRY_SUCCESS = "ADMIN_UPDATECOUNTRY_SUCCESS";
export const ADMIN_UPDATECOUNTRY_FAIL = "ADMIN_UPDATECOUNTRY_FAIL";
export const ADMIN_UPDATECOUNTRY_RESET = "ADMIN_UPDATECOUNTRY_RESET";

export const ADMIN_STATELIST_REQUEST = "ADMIN_STATELIST_REQUEST";
export const ADMIN_STATELIST_SUCCESS = "ADMIN_STATELIST_SUCCESS";
export const ADMIN_STATELIST_FAIL = "ADMIN_STATELIST_FAIL";

export const ADMIN_ADDSTATE_REQUEST = "ADMIN_ADDSTATE_REQUEST";
export const ADMIN_ADDSTATE_SUCCESS = "ADMIN_ADDSTATE_SUCCESS";
export const ADMIN_ADDSTATE_FAIL = "ADMIN_ADDSTATE_FAIL";
export const ADMIN_ADDSTATE_RESET = "ADMIN_ADDSTATE_RESET";

export const ADMIN_STATEDETAIL_REQUEST = "ADMIN_STATEDETAIL_REQUEST";
export const ADMIN_STATEDETAIL_SUCCESS = "ADMIN_STATEDETAIL_SUCCESS";
export const ADMIN_STATEDETAIL_FAIL = "ADMIN_STATEDETAIL_FAIL";
export const ADMIN_STATEDETAIL_RESET = "ADMIN_STATEDETAIL_RESET";

export const ADMIN_DELETESTATE_REQUEST = "ADMIN_DELETESTATE_REQUEST";
export const ADMIN_DELETESTATE_SUCCESS = "ADMIN_DELETESTATE_SUCCESS";
export const ADMIN_DELETESTATE_FAIL = "ADMIN_DELETESTATE_FAIL";

export const ADMIN_STATESTATUS_REQUEST = "ADMIN_STATESTATUS_REQUEST";
export const ADMIN_STATESTATUS_SUCCESS = "ADMIN_STATESTATUS_SUCCESS";
export const ADMIN_STATESTATUS_FAIL = "ADMIN_STATESTATUS_FAIL";

export const ADMIN_UPDATESTATE_REQUEST = "ADMIN_UPDATESTATE_REQUEST";
export const ADMIN_UPDATESTATE_SUCCESS = "ADMIN_UPDATESTATE_SUCCESS";
export const ADMIN_UPDATESTATE_FAIL = "ADMIN_UPDATESTATE_FAIL";
export const ADMIN_UPDATESTATE_RESET = "ADMIN_UPDATESTATE_RESET";

export const ADMIN_CITYLIST_REQUEST = "ADMIN_CITYLIST_REQUEST";
export const ADMIN_CITYLIST_SUCCESS = "ADMIN_CITYLIST_SUCCESS";
export const ADMIN_CITYLIST_FAIL = "ADMIN_CITYLIST_FAIL";

export const ADMIN_ADDCITY_REQUEST = "ADMIN_ADDCITY_REQUEST";
export const ADMIN_ADDCITY_SUCCESS = "ADMIN_ADDCITY_SUCCESS";
export const ADMIN_ADDCITY_FAIL = "ADMIN_ADDCITY_FAIL";
export const ADMIN_ADDCITY_RESET = "ADMIN_ADDCITY_RESET";

export const ADMIN_CITYDETAIL_REQUEST = "ADMIN_CITYDETAIL_REQUEST";
export const ADMIN_CITYDETAIL_SUCCESS = "ADMIN_CITYDETAIL_SUCCESS";
export const ADMIN_CITYDETAIL_FAIL = "ADMIN_CITYDETAIL_FAIL";

export const ADMIN_CITYSTATUS_REQUEST = "ADMIN_CITYSTATUS_REQUEST";
export const ADMIN_CITYSTATUS_SUCCESS = "ADMIN_CITYSTATUS_SUCCESS";
export const ADMIN_CITYSTATUS_FAIL = "ADMIN_CITYSTATUS_FAIL";

export const ADMIN_DELETECITY_REQUEST = "ADMIN_DELETECITY_REQUEST";
export const ADMIN_DELETECITY_SUCCESS = "ADMIN_DELETECITY_SUCCESS";
export const ADMIN_DELETECITY_FAIL = "ADMIN_DELETECITY_FAIL";

export const ADMIN_UPDATECITY_REQUEST = "ADMIN_UPDATECITY_REQUEST";
export const ADMIN_UPDATECITY_SUCCESS = "ADMIN_UPDATECITY_SUCCESS";
export const ADMIN_UPDATECITY_FAIL = "ADMIN_UPDATECITY_FAIL";
export const ADMIN_UPDATECITY_RESET = "ADMIN_UPDATECITY_RESET";

//* Startag Management

export const ADMIN_STARTAGLIST_REQUEST = "ADMIN_STARTAGLIST_REQUEST";
export const ADMIN_STARTAGLIST_SUCCESS = "ADMIN_STARTAGLIST_SUCCESS";
export const ADMIN_STARTAGLIST_FAIL = "ADMIN_STARTAGLIST_FAIL";

export const ADMIN_ADDSTARTAG_REQUEST = "ADMIN_ADDSTARTAG_REQUEST";
export const ADMIN_ADDSTARTAG_SUCCESS = "ADMIN_ADDSTARTAG_SUCCESS";
export const ADMIN_ADDSTARTAG_FAIL = "ADMIN_ADDSTARTAG_FAIL";
export const ADMIN_ADDSTARTAG_RESET = "ADMIN_ADDSTARTAG_RESET";

export const ADMIN_STARTAGDETAIL_REQUEST = "ADMIN_STARTAGDETAIL_REQUEST";
export const ADMIN_STARTAGDETAIL_SUCCESS = "ADMIN_STARTAGDETAIL_SUCCESS";
export const ADMIN_STARTAGDETAIL_FAIL = "ADMIN_STARTAGDETAIL_FAIL";

export const ADMIN_DELETESTARTAG_REQUEST = "ADMIN_DELETESTARTAG_REQUEST";
export const ADMIN_DELETESTARTAG_SUCCESS = "ADMIN_DELETESTARTAG_SUCCESS";
export const ADMIN_DELETESTARTAG_FAIL = "ADMIN_DELETESTARTAG_FAIL";
export const ADMIN_DELETESTARTAG_RESET = "ADMIN_DELETESTARTAG_RESET";

export const ADMIN_STARTAGSTATUS_REQUEST = "ADMIN_STARTAGSTATUS_REQUEST";
export const ADMIN_STARTAGSTATUS_SUCCESS = "ADMIN_STARTAGSTATUS_SUCCESS";
export const ADMIN_STARTAGSTATUS_FAIL = "ADMIN_STARTAGSTATUS_FAIL";

export const ADMIN_UPDATESTARTAG_REQUEST = "ADMIN_UPDATESTARTAG_REQUEST";
export const ADMIN_UPDATESTARTAG_SUCCESS = "ADMIN_UPDATESTARTAG_SUCCESS";
export const ADMIN_UPDATESTARTAG_FAIL = "ADMIN_UPDATESTARTAG_FAIL";
export const ADMIN_UPDATESTARTAG_RESET = "ADMIN_UPDATESTARTAG_RESET";

//*User Management

export const ADMIN_USERLIST_REQUEST = "ADMIN_USERLIST_REQUEST";
export const ADMIN_USERLIST_SUCCESS = "ADMIN_USERLIST_SUCCESS";
export const ADMIN_USERLIST_FAIL = "ADMIN_USERLIST_FAIL";

export const ADMIN_ADDUSER_REQUEST = "ADMIN_ADDUSER_REQUEST";
export const ADMIN_ADDUSER_SUCCESS = "ADMIN_ADDUSER_SUCCESS";
export const ADMIN_ADDUSER_FAIL = "ADMIN_ADDUSER_FAIL";
export const ADMIN_ADDUSER_RESET = "ADMIN_ADDUSER_RESET";

export const ADMIN_USERDETAIL_REQUEST = "ADMIN_USERDETAIL_REQUEST";
export const ADMIN_USERDETAIL_SUCCESS = "ADMIN_USERDETAIL_SUCCESS";
export const ADMIN_USERDETAIL_FAIL = "ADMIN_USERDETAIL_FAIL";

export const ADMIN_DELETEUSER_REQUEST = "ADMIN_DELETEUSER_REQUEST";
export const ADMIN_DELETEUSER_SUCCESS = "ADMIN_DELETEUSER_SUCCESS";
export const ADMIN_DELETEUSER_FAIL = "ADMIN_DELETEUSER_FAIL";
export const ADMIN_DELETEUSER_RESET = "ADMIN_DELETEUSER_RESET";

export const ADMIN_USERSTATUS_REQUEST = "ADMIN_USERSTATUS_REQUEST";
export const ADMIN_USERSTATUS_SUCCESS = "ADMIN_USERSTATUS_SUCCESS";
export const ADMIN_USERSTATUS_FAIL = "ADMIN_USERSTATUS_FAIL";

export const ADMIN_UPDATEUSER_REQUEST = "ADMIN_UPDATEUSER_REQUEST";
export const ADMIN_UPDATEUSER_SUCCESS = "ADMIN_UPDATEUSER_SUCCESS";
export const ADMIN_UPDATEUSER_FAIL = "ADMIN_UPDATEUSER_FAIL";
export const ADMIN_UPDATEUSER_RESET = "ADMIN_UPDATEUSER_RESET";

export const ADMIN_VERIFYREQUESTLIST_SUCCESS =
  "ADMIN_VERIFYREQUESTLIST_SUCCESS";
export const ADMIN_VERIFYREQUESTLIST_REQUEST =
  "ADMIN_VERIFYREQUESTLIST_REQUEST";
export const ADMIN_VERIFYREQUESTLIST_FAIL = "ADMIN_VERIFYREQUESTLIST_FAIL";

export const ADMIN_VERIFYREQUESTDETAIL_REQUEST =
  "ADMIN_VERIFYREQUESTDETAIL_REQUEST";
export const ADMIN_VERIFYREQUESTDETAIL_SUCCESS =
  "ADMIN_VERIFYREQUESTDETAIL_SUCCESS";
export const ADMIN_VERIFYREQUESTDETAIL_FAIL = "ADMIN_VERIFYREQUESTDETAIL_FAIL";

export const ADMIN_VERIFYING_REQUEST = "ADMIN_VERIFYING_REQUEST";
export const ADMIN_VERIFYING_SUCCESS = "ADMIN_VERIFYING_SUCCESS";
export const ADMIN_VERIFYING_FAIL = "ADMIN_VERIFYING_FAIL";
export const ADMIN_VERIFYING_RESET = "ADMIN_VERIFYING_RESET";

export const ADMIN_DROPPING_REQUEST = "ADMIN_DROPPING_REQUEST";
export const ADMIN_DROPPING_SUCCESS = "ADMIN_DROPPING_SUCCESS";
export const ADMIN_DROPPING_FAIL = "ADMIN_DROPPING_FAIL";
export const ADMIN_DROPPING_RESET = "ADMIN_DROPPING_RESET";

export const ADMIN_USERREPORTS_REQUEST = "ADMIN_USERREPORTS_REQUEST";
export const ADMIN_USERREPORTS_SUCCESS = "ADMIN_USERREPORTS_SUCCESS";
export const ADMIN_USERREPORTS_FAIL = "ADMIN_USERREPORTS_FAIL";

export const ADMIN_USERREPORTSTATUS_REQUEST = "ADMIN_USERREPORTSTATUS_REQUEST";
export const ADMIN_USERREPORTSTATUS_SUCCESS = "ADMIN_USERREPORTSTATUS_SUCCESS";
export const ADMIN_USERREPORTSTATUS_FAIL = "ADMIN_USERREPORTSTATUS_FAIL";

//*Post Management

export const ADMIN_POSTLIST_REQUEST = "ADMIN_POSTLIST_REQUEST";
export const ADMIN_POSTLIST_SUCCESS = "ADMIN_POSTLIST_SUCCESS";
export const ADMIN_POSTLIST_FAIL = "ADMIN_POSTLIST_FAIL";

export const ADMIN_POSTDETAIL_REQUEST = "ADMIN_POSTDETAIL_REQUEST";
export const ADMIN_POSTDETAIL_SUCCESS = "ADMIN_POSTDETAIL_SUCCESS";
export const ADMIN_POSTDETAIL_FAIL = "ADMIN_POSTDETAIL_FAIL";

export const ADMIN_REPORTLIST_REQUEST = "ADMIN_REPORTLIST_REQUEST";
export const ADMIN_REPORTLIST_SUCCESS = "ADMIN_REPORTLIST_SUCCESS";
export const ADMIN_REPORTLIST_FAIL = "ADMIN_REPORTLIST_FAIL";

export const ADMIN_REPORTSTATUS_REQUEST = "ADMIN_REPORTSTATUS_REQUEST";
export const ADMIN_REPORTSTATUS_SUCCESS = "ADMIN_REPORTSTATUS_SUCCESS";
export const ADMIN_REPORTSTATUS_FAIL = "ADMIN_REPORTSTATUS_FAIL";

export const ADMIN_POSTSTATUS_REQUEST = "ADMIN_POSTSTATUS_REQUEST";
export const ADMIN_POSTSTATUS_SUCCESS = "ADMIN_POSTSTATUS_SUCCESS";
export const ADMIN_POSTSTATUS_FAIL = "ADMIN_POSTSTATUS_FAIL";

export const ADMIN_POSTDELETE_REQUEST = "ADMIN_POSTDELETE_REQUEST";
export const ADMIN_POSTDELETE_SUCCESS = "ADMIN_POSTDELETE_SUCCESS";
export const ADMIN_POSTDELETE_FAIL = "ADMIN_POSTDELETE_SUCCESS";
export const ADMIN_POSTDELETE_RESET = "ADMIN_POSTDELETE_RESET";

//* Dashboard
export const ADMIN_DASHBOARD_REQUEST = "ADMIN_DASHBOARD_REQUEST";
export const ADMIN_DASHBOARD_SUCCESS = "ADMIN_DASHBOARD_SUCCESS";
export const ADMIN_DASHBOARD_FAIL = "ADMIN_DASHBOARD_FAIL";

//* Tax Management
export const ADMIN_TAXLIST_REQUEST = "ADMIN_TAXLIST_REQUEST";
export const ADMIN_TAXLIST_SUCCESS = "ADMIN_TAXLIST_SUCCESS";
export const ADMIN_TAXLIST_FAIL = "ADMIN_TAXLIST_FAIL";

export const ADMIN_TAXDETAIL_REQUEST = "ADMIN_TAXDETAIL_REQUEST";
export const ADMIN_TAXDETAIL_SUCCESS = "ADMIN_TAXDETAIL_SUCCESS";
export const ADMIN_TAXDETAIL_FAIL = "ADMIN_TAXDETAIL_FAIL";
export const ADMIN_TAXDETAIL_RESET = "ADMIN_TAXDETAIL_RESET";

export const ADMIN_TAXDELETE_REQUEST = "ADMIN_TAXDELETE_REQUEST";
export const ADMIN_TAXDELETE_SUCCESS = "ADMIN_TAXDELETE_SUCCESS";
export const ADMIN_TAXDELETE_FAIL = "ADMIN_TAXDELETE_FAIL";
export const ADMIN_TAXDELETE_RESET = "ADMIN_TAXDELETE_RESET";

export const ADMIN_TAXUPDATE_REQUEST = "ADMIN_TAXUPDATE_REQUEST";
export const ADMIN_TAXUPDATE_SUCCESS = "ADMIN_TAXUPDATE_SUCCESS";
export const ADMIN_TAXUPDATE_FAIL = "ADMIN_TAXUPDATE_FAIL";
export const ADMIN_TAXUPDATE_RESET = "ADMIN_TAXUPDATE_RESET";

export const ADMIN_TAXSTATUS_REQUEST = "ADMIN_TAXSTATUS_REQUEST";
export const ADMIN_TAXSTATUS_SUCCESS = "ADMIN_TAXSTATUS_SUCCESS";
export const ADMIN_TAXSTATUS_FAIL = "ADMIN_TAXSTATUS_FAIL";

export const ADMIN_ADDTAX_REQUEST = "ADMIN_ADDTAX_REQUEST";
export const ADMIN_ADDTAX_SUCCESS = "ADMIN_ADDTAX_SUCCESS";
export const ADMIN_ADDTAX_FAIL = "ADMIN_ADDTAX_FAIL";
export const ADMIN_ADDTAX_RESET = "ADMIN_ADDTAX_RESET";
